apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api
  namespace: apps
  labels:
    app: shop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-api
  template:
    metadata:
      labels:
        app: shop-api
    spec:
      containers:
      - name: shop-api
        image: docker.io/library/shop-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: JWKS_URL
          value: "http://keycloak.keycloak.svc.cluster.local/realms/company/protocol/openid-connect/certs"
        - name: DB_HOST
          value: "shop-postgres-postgresql.apps.svc.cluster.local"
        - name: DB_NAME
          value: "shopdb"
        - name: DB_USER
          value: "shop"
        - name: DB_PASS
          value: "shop_db_pass_123"
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shop-api
  namespace: apps
spec:
  selector:
    app: shop-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
